highlighter: rogue
name: Octocat's Wanderings
description: Chronicles of my adventures in coding and open source
url: "https://halitizgin.github.io"
lsi: false
exclude: [LICENCE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

#Build settings
permalink: pretty
theme: minima
